name: fluttering_phrases
description: Generate random noun phrases with an optional token to spice up names in your application.
version: 0.4.0
repository: https://github.com/parlough/fluttering_phrases

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
