name: fluttering_phrases
description: Generate random noun phrases with an optional token to spice up names in your application.
version: 0.2.0-nullsafety.0
homepage: https://github.com/parlough/fluttering_phrases

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
