name: fluttering_phrases
description: Generate random noun phrases with an optional token to spice up names in your application.
version: 0.3.1
homepage: https://github.com/parlough/fluttering_phrases

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.4
