name: fluttering_phrases
description: Generate random noun phrases with an optional token to spice up names in your application.
version: 0.1.0
homepage: https://github.com/parlough/fluttering_phrases

environment:
  sdk: '>=2.10.4 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
