name: fluttering_phrases
description:
  Generate random noun phrases with an optional token
  to spice up names in your application.
version: 0.5.0-wip
repository: https://github.com/parlough/fluttering_phrases

environment:
  sdk: ^3.0.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.24.2
